name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy auth
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun run clean
        
      - name: Typegen
        run: bun run typegen

      - name: Build workspace
        run: bun run build

      - name: Deploy auth to workers
        run: bun run --cwd apps/auth deploy

      - name: Deploy www to workers
        run: bun run --cwd apps/www deploy